[package]
name = "GetLocalInfo"
version = "0.1.0"
authors = ["liuqiang <liulcsy@qq.com>"]
description = "Getlocalinfo is a Rust crate that obtains local information"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.34.0"